### ISSUE TITLE
Configure Micrometer metrics for prometheus

### ISSUE THREAD

**Issue by rdjurin** [balcony-seats/vertx-helper#3]
Conigure micrometer metrics from config file.

Configuration:

```yaml
vertx:
  metrics:
   micrometer:
     enabled: true
     prometheus:
        enabled: true
        path: '/metrics'
```
