### ISSUE TITLE
Configure basic health check endpoint

### ISSUE THREAD

**Issue by rdjurin** [balcony-seats/vertx-helper#4]
Configure basic health check endpoint.
Provide support for defining custom health check handlers.

See: https://vertx.io/docs/vertx-health-check/java/#_using_vert_x_health_checks

Config:

```yaml
vertx:
  health-check:
    enabled: true
    path: '/health'
```
