### ISSUE TITLE
Kafka add support for creating consumer and producer from config

### ISSUE THREAD

**Issue by rdjurin** [balcony-seats/vertx-helper#40]
Support to create consumer and producer from configuration:

```yaml
kafka:
  enabled: true
  consumers:
    commonConfig:
      key.deserializer : 'org.apache.kafka.common.serialization.StringDeserializer'
      value.deserializer : 'org.apache.kafka.common.serialization.StringDeserializer'
    foo:
      client.id: foo
      topic: foo_topic
      group.id: foo
    bar:
      client.id: bar
      topic: bar_topic
      group.id: bar
  producers:
    commonConfig: 
      key.serializer : 'org.apache.kafka.common.serialization.StringSerializer'
      value.serializer : 'org.apache.kafka.common.serialization.StringSerializer'
    foo:
      client.id: foo
      topic: foo
    bar:
      client.id: bar
      topic: bar
  config:
    bootstrap.servers: 'server-1:9092,server-2:9092'
    security.protocol : 'SSL'
    ssl.enabled.protocols: 'TLSv1.2,TLSv1.1,TLSv1'
    ssl.keystore.location: 'keystore.jks'
    ssl.keystore.password: 'changeit'
    ssl.keystore.type: 'JKS'
    ssl.truststore.location: 'truststore.jks'
    ssl.truststore.password: 'password'
    ssl.truststore.type: 'JKS'

```
