### ISSUE TITLE
Configured JWTAuthProvider

### ISSUE THREAD

**Issue by rdjurin** [balcony-seats/vertx-helper#42]
Create JWTAuthProvider which is configured from configuration like this.

```yaml
clients:
  - issuer: jwks-uri-client
    jwks-uri:
      uri: 'http://localhost:8080/keys'
      proxy:
        host: 'localhost'`
        port: 8081
      cache:
        size: 2
        timeToLiveSeconds: 3600
  - issuer: jwks-pem-client
    jwks:
      - key-id: jwks-jwk-client-key-id
        algorithm: RS512
        public-key-pem: |
          -----BEGIN PUBLIC KEY-----
          ...
          -----END PUBLIC KEY-----
      - key-id: jwks-jwk-client-key-id-2
        algorithm: RS512
        public-key-pem: |
          -----BEGIN PUBLIC KEY-----
          ...
          -----END PUBLIC KEY-----

```
