### ISSUE TITLE
Support multiple database pools

### ISSUE THREAD

**Issue by rdjurin** [balcony-seats/vertx-helper#50]
Current `ConfigSqlPoolHelper` support only one database to configure from `database` configuration.

Add support for configuring databases by providing configuration name:

Example configuration:

```yaml
database:
  type: 'postgresql'
  host: 'host'
  port: port
  database: 'db'
  user: 'username'
  password: 'password'
  pool:
    max-size: 5
    max-wait-queue-size: -1
    connection-timeout: 30

database-2:
  type: 'postgresql'
  host: 'host'
  port: port
  database: 'db'
  user: 'username'
  password: 'password'
  pool:
    max-size: 5
    max-wait-queue-size: -1
    connection-timeout: 30

```

```java
io.github.balconyseats.vertx.helper.database.sql.ConfigSqlPoolHelper.create(vertx, config) //current implemenation with default database prefix
io.github.balconyseats.vertx.helper.database.sql.ConfigSqlPoolHelper.create(vertx, config, prefix) //create with prefix
```
